const mongoose  = require("mongoose")
const workoutSchema = mongoose.Schema({
    trainerUsername:{
        type:String,
        required:true
    },
    memberUsername:{
        type:String,
        unique:true,
        required:true
    },
    planName:{
        type:String,
        required:true
    },
    goal:{
        type:String,
        required:true
    },
    workouts:[
        {
            day:{type:String},
            exercises:[
                {
                    name:String,
                    sets:Number,
                    reps:Number
                }
            ]
        }
    ],
    duration:{
        type:Number,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    expiredAt:{
        type:Date,
        required:true
    }
})
module.exports = mongoose.model("WorkoutPlan",workoutSchema)