const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
const app = express()
const classroute = require("./router/Class") 
const member = require("./router/member")
const trainerroute = require("./router/trainer")
const geminirouter = require("./router/gemini")
const attendanceRoute = require("./router/Attendance")
const workoutRouter = require("./router/WorkoutPlan")
app.use(express.static("./public"))
const paymentrouter = require("./router/payment")
const striperoute = require("./router/stripe")
const multerroute = require("./router/multer")
const memberplanroute  = require("./router/memberplan")
const dietplanRoute = require("./router/Dietplan")
const supplimentroute = require("./router/Suppliment")
require("./router/classchecker")
require("./router/dietplanchecker")
require("./router/membershipchecker")
require("./router/workoutplanchecker")
app.use("/webhook", require("./router/webhook"));
require("dotenv").config()
app.use(express.json())
app.use(cors())
const authrouter = require("./router/addgym")
const port = process.env.PORT
const createConnection = async()=>{
await mongoose.connect(process.env.MONGODB_URL).then(()=>{
        console.log("MongoDb connection is successfully")
        app.listen(port,()=>{
            console.log("server is running on "+port)
        })
}).catch((error)=>{
        console.log(error)
})
}
createConnection()
app.use("/memberplan",memberplanroute)
app.use("/workout",workoutRouter)
app.use("/get",member)
app.use("/auth",authrouter)
app.use("/multer",multerroute)
app.use("/trainer",trainerroute)
app.use("/diet",dietplanRoute)
app.use("/suppliment",supplimentroute)
app.use("/ai",geminirouter)
app.use("/Attendance",attendanceRoute)
app.use("/class",classroute)
app.use("/stripes",striperoute)
app.use("/payment",paymentrouter)