const express = require("express")
const router = express.Router()
const {getSchedule,getDietplan,adddietplandata,addSchedule,getaidietplan,deletedietplan,getworkoutplan,deleteschedule} = require("../controller/gemini")
router.post("/createSchedule",getSchedule)
router.post("/creatediet",getDietplan)
router.post("/adddatadb",adddietplandata)
router.post("/addschedule",addSchedule)
router.post("/getaibaseddietplan",getaidietplan)
router.post("/deletediet",deletedietplan)
router.post("/getworkoutplan",getworkoutplan)
router.post("/deleteschedule",deleteschedule)
module.exports = router