const express = require("express")
const {getmemberdetails, deleteMember,getmemberbyID,updatemember,getmemberdetailss,getmemberDetailBytrainer,authmember,getmembersusernamebyadmin,getnumberofmembers} = require("../controller/addmember")
const router=  express.Router()
router.post("/getmembers",getmemberdetails)
router.post("/deletemember",deleteMember)
router.post("/getmemberbyid",getmemberbyID)
router.post("/updatemember",updatemember)
router.post("/getmemberss",getmemberdetailss)
router.post("/getmemberbyTrainer",getmemberDetailBytrainer)
router.post("/authmember",authmember)
router.post("/getmemberusernamebyadmin",getmembersusernamebyadmin)
router.post("/getnumberofmembers",getnumberofmembers)
module.exports = router